
# include "../scalar.hpp"
int ScalarProgram::num_registers()
{
    return 101;
}

std::vector<std::string> ScalarProgram::vars_used()
{
    return {"b:0,0", "a:0,2", "b:1,0", "a:0,0", "b:1,1", "a:2,2", "a:2,0", "b:2,2", "a:0,1", "b:2,1", "b:0,1", "a:1,0", "a:1,1", "b:0,2", "b:1,2", "a:1,2", "a:2,1", "b:2,0"};
}

std::vector<ctxt> ScalarProgram::computation(std::map<std::string, ctxt> locs, RuntimeContext &info)
{
    seal::RelinKeys rk = info.keys->rk;
    ctxt regs[num_registers()];
    regs[0] = locs["a:0,0"];
    regs[1] = locs["b:0,0"];
    info.eval->multiply(regs[0], regs[1], regs[2]);
    info.eval->relinearize_inplace(regs[2], rk);
    regs[3] = locs["a:0,1"];
    regs[4] = locs["b:1,0"];
    info.eval->multiply(regs[3], regs[4], regs[5]);
    info.eval->relinearize_inplace(regs[5], rk);
    info.eval->add(regs[2], regs[5], regs[6]);
    regs[7] = locs["a:0,2"];
    info.eval->multiply(regs[7], locs["b:2,0"], regs[8]);
    info.eval->relinearize_inplace(regs[8], rk);
    info.eval->add(regs[6], regs[8], regs[9]);
    regs[10] = locs["a:1,0"];
    regs[11] = locs["b:0,1"];
    info.eval->multiply(regs[10], regs[11], regs[12]);
    info.eval->relinearize_inplace(regs[12], rk);
    regs[13] = locs["a:1,1"];
    regs[14] = locs["b:1,1"];
    info.eval->multiply(regs[13], regs[14], regs[15]);
    info.eval->relinearize_inplace(regs[15], rk);
    info.eval->add(regs[12], regs[15], regs[16]);
    regs[17] = locs["a:1,2"];
    info.eval->multiply(regs[17], locs["b:2,1"], regs[18]);
    info.eval->relinearize_inplace(regs[18], rk);
    info.eval->add(regs[16], regs[18], regs[19]);
    regs[20] = locs["b:0,2"];
    info.eval->multiply(locs["a:2,0"], regs[20], regs[21]);
    info.eval->relinearize_inplace(regs[21], rk);
    regs[22] = locs["b:1,2"];
    info.eval->multiply(locs["a:2,1"], regs[22], regs[23]);
    info.eval->relinearize_inplace(regs[23], rk);
    info.eval->add(regs[21], regs[23], regs[24]);
    info.eval->multiply(locs["a:2,2"], locs["b:2,2"], regs[25]);
    info.eval->relinearize_inplace(regs[25], rk);
    info.eval->add(regs[24], regs[25], regs[26]);
    info.eval->multiply(regs[19], regs[26], regs[27]);
    info.eval->relinearize_inplace(regs[27], rk);
    info.eval->multiply(locs["a:2,0"], regs[11], regs[28]);
    info.eval->relinearize_inplace(regs[28], rk);
    info.eval->multiply(locs["a:2,1"], regs[14], regs[29]);
    info.eval->relinearize_inplace(regs[29], rk);
    info.eval->add(regs[28], regs[29], regs[30]);
    info.eval->multiply(locs["a:2,2"], locs["b:2,1"], regs[31]);
    info.eval->relinearize_inplace(regs[31], rk);
    info.eval->add(regs[30], regs[31], regs[32]);
    info.eval->multiply(regs[10], regs[20], regs[33]);
    info.eval->relinearize_inplace(regs[33], rk);
    info.eval->multiply(regs[13], regs[22], regs[34]);
    info.eval->relinearize_inplace(regs[34], rk);
    info.eval->add(regs[33], regs[34], regs[35]);
    info.eval->multiply(regs[17], locs["b:2,2"], regs[36]);
    info.eval->relinearize_inplace(regs[36], rk);
    info.eval->add(regs[35], regs[36], regs[37]);
    info.eval->multiply(regs[32], regs[37], regs[38]);
    info.eval->relinearize_inplace(regs[38], rk);
    info.eval->add(regs[27], regs[38], regs[39]);
    info.eval->multiply(regs[9], regs[39], regs[40]);
    info.eval->relinearize_inplace(regs[40], rk);
    info.eval->multiply(regs[0], regs[11], regs[41]);
    info.eval->relinearize_inplace(regs[41], rk);
    info.eval->multiply(regs[3], regs[14], regs[42]);
    info.eval->relinearize_inplace(regs[42], rk);
    info.eval->add(regs[41], regs[42], regs[43]);
    info.eval->multiply(regs[7], locs["b:2,1"], regs[44]);
    info.eval->relinearize_inplace(regs[44], rk);
    info.eval->add(regs[43], regs[44], regs[45]);
    info.eval->multiply(regs[10], regs[1], regs[46]);
    info.eval->relinearize_inplace(regs[46], rk);
    info.eval->multiply(regs[13], regs[4], regs[47]);
    info.eval->relinearize_inplace(regs[47], rk);
    info.eval->add(regs[46], regs[47], regs[48]);
    info.eval->multiply(regs[17], locs["b:2,0"], regs[49]);
    info.eval->relinearize_inplace(regs[49], rk);
    info.eval->add(regs[48], regs[49], regs[50]);
    info.eval->multiply(locs["a:2,0"], regs[20], regs[51]);
    info.eval->relinearize_inplace(regs[51], rk);
    info.eval->multiply(locs["a:2,1"], regs[22], regs[52]);
    info.eval->relinearize_inplace(regs[52], rk);
    info.eval->add(regs[51], regs[52], regs[53]);
    info.eval->multiply(locs["a:2,2"], locs["b:2,2"], regs[54]);
    info.eval->relinearize_inplace(regs[54], rk);
    info.eval->add(regs[53], regs[54], regs[55]);
    info.eval->multiply(regs[50], regs[55], regs[56]);
    info.eval->relinearize_inplace(regs[56], rk);
    info.eval->multiply(locs["a:2,0"], regs[1], regs[57]);
    info.eval->relinearize_inplace(regs[57], rk);
    info.eval->multiply(locs["a:2,1"], regs[4], regs[58]);
    info.eval->relinearize_inplace(regs[58], rk);
    info.eval->add(regs[57], regs[58], regs[59]);
    info.eval->multiply(locs["a:2,2"], locs["b:2,0"], regs[60]);
    info.eval->relinearize_inplace(regs[60], rk);
    info.eval->add(regs[59], regs[60], regs[61]);
    info.eval->multiply(regs[10], regs[20], regs[62]);
    info.eval->relinearize_inplace(regs[62], rk);
    info.eval->multiply(regs[13], regs[22], regs[63]);
    info.eval->relinearize_inplace(regs[63], rk);
    info.eval->add(regs[62], regs[63], regs[64]);
    info.eval->multiply(regs[17], locs["b:2,2"], regs[65]);
    info.eval->relinearize_inplace(regs[65], rk);
    info.eval->add(regs[64], regs[65], regs[66]);
    info.eval->multiply(regs[61], regs[66], regs[67]);
    info.eval->relinearize_inplace(regs[67], rk);
    info.eval->add(regs[56], regs[67], regs[68]);
    info.eval->multiply(regs[45], regs[68], regs[69]);
    info.eval->relinearize_inplace(regs[69], rk);
    info.eval->sub(regs[40], regs[69], regs[70]);
    info.eval->multiply(regs[0], regs[20], regs[71]);
    info.eval->relinearize_inplace(regs[71], rk);
    info.eval->multiply(regs[3], regs[22], regs[72]);
    info.eval->relinearize_inplace(regs[72], rk);
    info.eval->add(regs[71], regs[72], regs[73]);
    info.eval->multiply(regs[7], locs["b:2,2"], regs[74]);
    info.eval->relinearize_inplace(regs[74], rk);
    info.eval->add(regs[73], regs[74], regs[75]);
    info.eval->multiply(regs[10], regs[1], regs[76]);
    info.eval->relinearize_inplace(regs[76], rk);
    info.eval->multiply(regs[13], regs[4], regs[77]);
    info.eval->relinearize_inplace(regs[77], rk);
    info.eval->add(regs[76], regs[77], regs[78]);
    info.eval->multiply(regs[17], locs["b:2,0"], regs[79]);
    info.eval->relinearize_inplace(regs[79], rk);
    info.eval->add(regs[78], regs[79], regs[80]);
    info.eval->multiply(locs["a:2,0"], regs[11], regs[81]);
    info.eval->relinearize_inplace(regs[81], rk);
    info.eval->multiply(locs["a:2,1"], regs[14], regs[82]);
    info.eval->relinearize_inplace(regs[82], rk);
    info.eval->add(regs[81], regs[82], regs[83]);
    info.eval->multiply(locs["a:2,2"], locs["b:2,1"], regs[84]);
    info.eval->relinearize_inplace(regs[84], rk);
    info.eval->add(regs[83], regs[84], regs[85]);
    info.eval->multiply(regs[80], regs[85], regs[86]);
    info.eval->relinearize_inplace(regs[86], rk);
    info.eval->multiply(locs["a:2,0"], regs[1], regs[87]);
    info.eval->relinearize_inplace(regs[87], rk);
    info.eval->multiply(locs["a:2,1"], regs[4], regs[88]);
    info.eval->relinearize_inplace(regs[88], rk);
    info.eval->add(regs[87], regs[88], regs[89]);
    info.eval->multiply(locs["a:2,2"], locs["b:2,0"], regs[90]);
    info.eval->relinearize_inplace(regs[90], rk);
    info.eval->add(regs[89], regs[90], regs[91]);
    info.eval->multiply(regs[10], regs[11], regs[92]);
    info.eval->relinearize_inplace(regs[92], rk);
    info.eval->multiply(regs[13], regs[14], regs[93]);
    info.eval->relinearize_inplace(regs[93], rk);
    info.eval->add(regs[92], regs[93], regs[94]);
    info.eval->multiply(regs[17], locs["b:2,1"], regs[95]);
    info.eval->relinearize_inplace(regs[95], rk);
    info.eval->add(regs[94], regs[95], regs[96]);
    info.eval->multiply(regs[91], regs[96], regs[97]);
    info.eval->relinearize_inplace(regs[97], rk);
    info.eval->add(regs[86], regs[97], regs[98]);
    info.eval->multiply(regs[75], regs[98], regs[99]);
    info.eval->relinearize_inplace(regs[99], rk);
    info.eval->add(regs[70], regs[99], regs[100]);
    std::vector<ctxt> answer;
    answer.push_back(regs[100]);
    return answer;
}
    