
# include "../scalar.hpp"
int ScalarProgram::num_registers()
{
    return 100;
}

std::vector<std::string> ScalarProgram::vars_used()
{
    return {"a:0,3", "b:1,1", "a:1,1", "a:0,1", "a:3,0", "a:1,2", "a:3,1", "b:2,0", "a:3,3", "b:2,1", "a:2,0", "b:1,2", "b:0,0", "a:1,3", "b:0,1", "a:1,0", "a:2,3", "a:0,2", "a:0,0", "a:2,2", "a:3,2", "b:2,2", "b:1,0", "b:0,2", "a:2,1"};
}

std::vector<ctxt> ScalarProgram::computation(std::map<std::string, ctxt> locs, RuntimeContext &info)
{
    seal::RelinKeys rk = info.keys->rk;
    ctxt regs[num_registers()];
    regs[0] = locs["b:0,0"];
    regs[1] = locs["a:0,0"];
    info.eval->multiply(regs[0], regs[1], regs[2]);
    info.eval->relinearize_inplace(regs[2], rk);
    regs[3] = locs["b:0,1"];
    regs[4] = locs["a:0,1"];
    info.eval->multiply(regs[3], regs[4], regs[5]);
    info.eval->relinearize_inplace(regs[5], rk);
    info.eval->add(regs[2], regs[5], regs[6]);
    regs[7] = locs["b:0,2"];
    regs[8] = locs["a:0,2"];
    info.eval->multiply(regs[7], regs[8], regs[9]);
    info.eval->relinearize_inplace(regs[9], rk);
    info.eval->add(regs[6], regs[9], regs[10]);
    regs[11] = locs["b:1,0"];
    regs[12] = locs["a:1,0"];
    info.eval->multiply(regs[11], regs[12], regs[13]);
    info.eval->relinearize_inplace(regs[13], rk);
    info.eval->add(regs[10], regs[13], regs[14]);
    regs[15] = locs["b:1,1"];
    regs[16] = locs["a:1,1"];
    info.eval->multiply(regs[15], regs[16], regs[17]);
    info.eval->relinearize_inplace(regs[17], rk);
    info.eval->add(regs[14], regs[17], regs[18]);
    regs[19] = locs["b:1,2"];
    regs[20] = locs["a:1,2"];
    info.eval->multiply(regs[19], regs[20], regs[21]);
    info.eval->relinearize_inplace(regs[21], rk);
    info.eval->add(regs[18], regs[21], regs[22]);
    info.eval->multiply(locs["b:2,0"], locs["a:2,0"], regs[23]);
    info.eval->relinearize_inplace(regs[23], rk);
    info.eval->add(regs[22], regs[23], regs[24]);
    info.eval->multiply(locs["b:2,1"], locs["a:2,1"], regs[25]);
    info.eval->relinearize_inplace(regs[25], rk);
    info.eval->add(regs[24], regs[25], regs[26]);
    info.eval->multiply(locs["b:2,2"], locs["a:2,2"], regs[27]);
    info.eval->relinearize_inplace(regs[27], rk);
    info.eval->add(regs[26], regs[27], regs[28]);
    regs[29] = locs["b:0,0"];
    info.eval->multiply(regs[29], regs[4], regs[30]);
    info.eval->relinearize_inplace(regs[30], rk);
    regs[31] = locs["b:0,1"];
    info.eval->multiply(regs[31], regs[8], regs[32]);
    info.eval->relinearize_inplace(regs[32], rk);
    info.eval->add(regs[30], regs[32], regs[33]);
    regs[34] = locs["b:0,2"];
    regs[35] = locs["a:0,3"];
    info.eval->multiply(regs[34], regs[35], regs[36]);
    info.eval->relinearize_inplace(regs[36], rk);
    info.eval->add(regs[33], regs[36], regs[37]);
    regs[38] = locs["b:1,0"];
    info.eval->multiply(regs[38], regs[16], regs[39]);
    info.eval->relinearize_inplace(regs[39], rk);
    info.eval->add(regs[37], regs[39], regs[40]);
    regs[41] = locs["b:1,1"];
    info.eval->multiply(regs[41], regs[20], regs[42]);
    info.eval->relinearize_inplace(regs[42], rk);
    info.eval->add(regs[40], regs[42], regs[43]);
    regs[44] = locs["b:1,2"];
    regs[45] = locs["a:1,3"];
    info.eval->multiply(regs[44], regs[45], regs[46]);
    info.eval->relinearize_inplace(regs[46], rk);
    info.eval->add(regs[43], regs[46], regs[47]);
    info.eval->multiply(locs["b:2,0"], locs["a:2,1"], regs[48]);
    info.eval->relinearize_inplace(regs[48], rk);
    info.eval->add(regs[47], regs[48], regs[49]);
    info.eval->multiply(locs["b:2,1"], locs["a:2,2"], regs[50]);
    info.eval->relinearize_inplace(regs[50], rk);
    info.eval->add(regs[49], regs[50], regs[51]);
    info.eval->multiply(locs["b:2,2"], locs["a:2,3"], regs[52]);
    info.eval->relinearize_inplace(regs[52], rk);
    info.eval->add(regs[51], regs[52], regs[53]);
    regs[54] = locs["b:0,0"];
    info.eval->multiply(regs[54], regs[12], regs[55]);
    info.eval->relinearize_inplace(regs[55], rk);
    regs[56] = locs["b:0,1"];
    info.eval->multiply(regs[56], regs[16], regs[57]);
    info.eval->relinearize_inplace(regs[57], rk);
    info.eval->add(regs[55], regs[57], regs[58]);
    regs[59] = locs["b:0,2"];
    info.eval->multiply(regs[59], regs[20], regs[60]);
    info.eval->relinearize_inplace(regs[60], rk);
    info.eval->add(regs[58], regs[60], regs[61]);
    regs[62] = locs["b:1,0"];
    info.eval->multiply(regs[62], locs["a:2,0"], regs[63]);
    info.eval->relinearize_inplace(regs[63], rk);
    info.eval->add(regs[61], regs[63], regs[64]);
    regs[65] = locs["b:1,1"];
    info.eval->multiply(regs[65], locs["a:2,1"], regs[66]);
    info.eval->relinearize_inplace(regs[66], rk);
    info.eval->add(regs[64], regs[66], regs[67]);
    regs[68] = locs["b:1,2"];
    info.eval->multiply(regs[68], locs["a:2,2"], regs[69]);
    info.eval->relinearize_inplace(regs[69], rk);
    info.eval->add(regs[67], regs[69], regs[70]);
    info.eval->multiply(locs["b:2,0"], locs["a:3,0"], regs[71]);
    info.eval->relinearize_inplace(regs[71], rk);
    info.eval->add(regs[70], regs[71], regs[72]);
    info.eval->multiply(locs["b:2,1"], locs["a:3,1"], regs[73]);
    info.eval->relinearize_inplace(regs[73], rk);
    info.eval->add(regs[72], regs[73], regs[74]);
    info.eval->multiply(locs["b:2,2"], locs["a:3,2"], regs[75]);
    info.eval->relinearize_inplace(regs[75], rk);
    info.eval->add(regs[74], regs[75], regs[76]);
    regs[77] = locs["b:0,0"];
    info.eval->multiply(regs[77], regs[16], regs[78]);
    info.eval->relinearize_inplace(regs[78], rk);
    regs[79] = locs["b:0,1"];
    info.eval->multiply(regs[79], regs[20], regs[80]);
    info.eval->relinearize_inplace(regs[80], rk);
    info.eval->add(regs[78], regs[80], regs[81]);
    regs[82] = locs["b:0,2"];
    info.eval->multiply(regs[82], regs[45], regs[83]);
    info.eval->relinearize_inplace(regs[83], rk);
    info.eval->add(regs[81], regs[83], regs[84]);
    regs[85] = locs["b:1,0"];
    info.eval->multiply(regs[85], locs["a:2,1"], regs[86]);
    info.eval->relinearize_inplace(regs[86], rk);
    info.eval->add(regs[84], regs[86], regs[87]);
    regs[88] = locs["b:1,1"];
    info.eval->multiply(regs[88], locs["a:2,2"], regs[89]);
    info.eval->relinearize_inplace(regs[89], rk);
    info.eval->add(regs[87], regs[89], regs[90]);
    regs[91] = locs["b:1,2"];
    info.eval->multiply(regs[91], locs["a:2,3"], regs[92]);
    info.eval->relinearize_inplace(regs[92], rk);
    info.eval->add(regs[90], regs[92], regs[93]);
    info.eval->multiply(locs["b:2,0"], locs["a:3,1"], regs[94]);
    info.eval->relinearize_inplace(regs[94], rk);
    info.eval->add(regs[93], regs[94], regs[95]);
    info.eval->multiply(locs["b:2,1"], locs["a:3,2"], regs[96]);
    info.eval->relinearize_inplace(regs[96], rk);
    info.eval->add(regs[95], regs[96], regs[97]);
    info.eval->multiply(locs["b:2,2"], locs["a:3,3"], regs[98]);
    info.eval->relinearize_inplace(regs[98], rk);
    info.eval->add(regs[97], regs[98], regs[99]);
    std::vector<ctxt> answer;
    answer.push_back(regs[28]);
    answer.push_back(regs[53]);
    answer.push_back(regs[76]);
    answer.push_back(regs[99]);
    return answer;
}
    